
import React from 'react';
import { Sprout, CloudRain, ShoppingBag, MessageSquare, ShieldAlert, Leaf, HelpCircle, Mic, BookOpen, Zap, Volume2, Layers } from 'lucide-react';
import { Language } from './types';

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    appTitle: "Kissan AI",
    welcome: "Welcome, Farmer",
    cropDoctor: "Crop Doctor",
    marketHub: "Market Hub",
    weather: "Weather",
    aiAssistant: "AI Assistant",
    sustainableTips: "Green Tips",
    scanCrop: "Scan Crop for Diseases",
    askAnything: "Ask about farming...",
    searchPlaceholder: "Search crops, prices, or diseases...",
    lowDataMode: "Low Data Mode",
    language: "Language",
    voiceActive: "Listening...",
    uploadImage: "Upload Photo",
    analyze: "Analyze",
    smartSearch: "Smart Voice Search",
    alertCenter: "Climate Alert Center",
    sendSms: "Send Emergency SMS",
    triggerAlarm: "Sound Farm Alarm",
    smsSuccess: "Emergency SMS sent to your contacts!",
    alarmPlaying: "Alarm active...",
    secureCropDesc: "Protect your harvest from sudden weather changes.",
    manageContacts: "Manage Contacts",
    addContact: "Add Emergency Number",
    noContacts: "No emergency contacts added yet.",
    contactPlaceholder: "Enter 10-digit mobile number",
    saveContact: "Save Contact",
    maxContacts: "You can add up to 3 emergency contacts.",
    voiceHelp: "Voice Help Assistant",
    askQuestion: "Ask your question...",
    helpTopics: "Popular Help Topics",
    speechToSpeech: "Talk to AI",
    multiLangSearch: "Multi-Language Search",
    voiceSearchBtn: "Search by Voice",
    textSearchBtn: "Search by Text",
    farmLedger: "Farm Ledger",
    schemeFinder: "Govt Schemes",
    voiceResponse: "Voice Assistant",
    todaysTasks: "Today's Tasks",
    addActivity: "Add Activity",
    activityType: "Activity Type",
    cropName: "Crop Name",
    activityDate: "Date",
    activityDetails: "Details",
    cost: "Cost (₹)",
    yield: "Yield (kg)",
    notes: "Notes",
    noActivities: "No activities logged yet",
    sowing: "Sowing",
    irrigation: "Irrigation",
    fertilizer: "Fertilizer Application",
    pesticide: "Pesticide Spray",
    harvesting: "Harvesting",
    weeding: "Weeding",
    pruning: "Pruning",
    other: "Other",
    eligibility: "Eligibility",
    benefits: "Benefits",
    applyNow: "Apply Now",
    deadline: "Application Deadline",
    noSchemes: "No schemes available",
    subsidy: "Subsidy",
    insurance: "Insurance",
    loan: "Loan",
    training: "Training",
    infrastructure: "Infrastructure",
    minimumLand: "Minimum Land Holding",
    state: "State",
    soilAdvisor: "Soil Advisor",
    soilCrop: "Soil-Crop Match",
  },
  [Language.TELUGU]: {
    appTitle: "కిసాన్ AI",
    welcome: "స్వాగతం, రైతు సోదరా",
    cropDoctor: "పంట వైద్యుడు",
    marketHub: "మార్కెట్ ధరలు",
    weather: "వాతావరణం",
    aiAssistant: "AI సహాయకుడు",
    sustainableTips: "సేంద్రియ చిట్కాలు",
    scanCrop: "పంట వ్యాధిని తనిఖీ చేయండి",
    askAnything: "వ్యవసాయం గురించి అడగండి...",
    searchPlaceholder: "పంటలు, ధరలు లేదా వ్యాధుల కోసం వెతకండి...",
    lowDataMode: "తక్కువ డేటా మోడ్",
    language: "భాష",
    voiceActive: "వింటున్నాను...",
    uploadImage: "ఫోటో అప్‌లోడ్",
    analyze: "విశ్లేషించు",
    smartSearch: "స్మార్ట్ వాయిస్ సెర్చ్",
    alertCenter: "వాతావరణ హెచ్చరిక కేంద్రం",
    sendSms: "ఎమర్జెన్సీ SMS పంపండి",
    triggerAlarm: "అలారం మోగించండి",
    smsSuccess: "మీ కాంటాక్ట్‌లకు ఎమర్జెన్సీ SMS పంపబడింది!",
    alarmPlaying: "అలారం మోగుతోంది...",
    secureCropDesc: "హఠాత్తుగా వచ్చే వాతావరణ మార్పుల నుండి మీ పంటను రక్షించుకోండి.",
    manageContacts: "కాంటాక్ట్‌లను నిర్వహించండి",
    addContact: "ఎమర్జెన్సీ నంబర్‌ను జోడించండి",
    noContacts: "ఇంకా ఏ ఎమర్జెన్సీ కాంటాక్ట్‌లు జోడించబడలేదు.",
    contactPlaceholder: "10 అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి",
    saveContact: "సంపర్కను సేవ్ చేయండి",
    maxContacts: "మీరు గరిష్టంగా 3 ఎమర్జెన్సీ సంపర్కలను జోడించవచ్చు.",
    voiceHelp: "వాయిస్ హెల్ప్ సహాయకుడు",
    askQuestion: "మీ ప్రశ్నను అడగండి...",
    helpTopics: "జనప్రియ సహాయ విషయాలు",
    speechToSpeech: "AIతో మాట్లాడండి",
    multiLangSearch: "బహు-భాష సెర్చ్",
    voiceSearchBtn: "వాయిస్ ద్వారా సెర్చ్",
    textSearchBtn: "టెక్స్ట్ ద్వారా సెర్చ్",
    farmLedger: "చేనేత రిపోర్టు",
    schemeFinder: "ప్రభుత్వ పథకాలు",
    voiceResponse: "వాయిస్ సహాయకుడు",
    todaysTasks: "ఈ రోజు కార్యాచరణలు",
    addActivity: "కార్యాచరణ జోడించండి",
    activityType: "కార్యాచరణ రకం",
    cropName: "పంట పేరు",
    activityDate: "తేదీ",
    activityDetails: "వివరాలు",
    cost: "ఖర్చు (₹)",
    yield: "దిగుబడి (కిలోలు)",
    notes: "గమనికలు",
    noActivities: "ఇంకా కార్యాచరణలు నమోదు చేయబడలేదు",
    sowing: "విత్తనం",
    irrigation: "నీటిపారుదల",
    fertilizer: "ఎరువు ఉపయోగం",
    pesticide: "పురుగుమందు స్ప్రే",
    harvesting: "పంట కోత",
    weeding: "కలుపు తొలగింపు",
    pruning: "కొమ్ములు కత్తిరింపు",
    other: "ఇతరులు",
    eligibility: "అర్హత",
    benefits: "ప్రయోజనాలు",
    applyNow: "ఇప్పుడు ఆవేదనం చేయండి",
    deadline: "ఆవేదన సమయ సीమ",
    noSchemes: "ఎటువంటి పథకాలు అందుబాటులో లేవు",
    subsidy: "సబ్సిడీ",
    insurance: "బీమా",
    loan: "రుణం",
    training: "శిక్షణ",
    infrastructure: "సమావేశ సదుపాయాలు",
    minimumLand: "కనిష్ట ల్యాండ్ హోల్డింగ్",
    state: "రాష్ట్రం",
    soilAdvisor: "నేల సలహాదారు",
    soilCrop: "నేల-పంట సరిపోల",
  },
  [Language.HINDI]: {
    appTitle: "किसान AI",
    welcome: "नमस्ते, किसान भाई",
    cropDoctor: "फसल डॉक्टर",
    marketHub: "मंडी भाव",
    weather: "मौसम",
    aiAssistant: "AI सहायक",
    sustainableTips: "जैविक सुझाव",
    scanCrop: "फसल रोग की जांच करें",
    askAnything: "खेती के बारे में पूछें...",
    searchPlaceholder: "फसलें, कीमतें या रोग खोजें...",
    lowDataMode: "कम डेटा मोड",
    language: "भाषा",
    voiceActive: "सुन रहा हूँ...",
    uploadImage: "फोटो अपलोड",
    analyze: "विश्लेषण करें",
    smartSearch: "स्मार्ट वॉयस सर्च",
    alertCenter: "जलवायु अलर्ट केंद्र",
    sendSms: "आपातकालीन SMS भेजें",
    triggerAlarm: "खेत अलार्म बजाएं",
    smsSuccess: "आपके संपर्कों को आपातकालीन SMS भेज दिया गया है!",
    alarmPlaying: "अलार्म बज रहा है...",
    secureCropDesc: "अचानक मौसम परिवर्तन से अपनी फसल की रक्षा करें।",
    manageContacts: "संपर्क प्रबंधित करें",
    addContact: "आपातकालीन नंबर जोड़ें",
    noContacts: "अभी तक कोई आपातकालीन संपर्क नहीं जोड़ा गया है।",
    contactPlaceholder: "10 अंकों का मोबाइल नंबर दर्ज करें",
    saveContact: "सँपर्क सहेजें",
    maxContacts: "आप अधिकतम 3 आपातकालीन सँपर्क जोड़ सकते हैं।",
    voiceHelp: "वॉयस हेल्प सहायक",
    askQuestion: "अपना प्रश्न पूछें...",
    helpTopics: "लोकप्रिय सहायता विषय",
    speechToSpeech: "AI से बात करें",
    multiLangSearch: "बहुभाषी खोज",
    voiceSearchBtn: "वॉयस से खोजें",
    textSearchBtn: "टेक्स्ट से खोजें",
    farmLedger: "खेत पत्रिका",
    schemeFinder: "सरकारी योजनाएं",
    voiceResponse: "वॉइस सहायक",
    todaysTasks: "आज के कार्य",
    addActivity: "गतिविधि जोड़ें",
    activityType: "गतिविधि प्रकार",
    cropName: "फसल का नाम",
    activityDate: "तारीख",
    activityDetails: "विवरण",
    cost: "लागत (₹)",
    yield: "उपज (किग्रा)",
    notes: "नोट्स",
    noActivities: "अभी तक कोई गतिविधि दर्ज नहीं की गई है",
    sowing: "बुवाई",
    irrigation: "सिंचाई",
    fertilizer: "खाद अनुप्रयोग",
    pesticide: "कीटनाशक स्प्रे",
    harvesting: "फसल कटाई",
    weeding: "निराई",
    pruning: "छँटाई",
    other: "अन्य",
    eligibility: "पात्रता",
    benefits: "लाभ",
    applyNow: "अभी आवेदन करें",
    deadline: "आवेदन की समय सीमा",
    noSchemes: "कोई योजना उपलब्ध नहीं है",
    subsidy: "सब्सिडी",
    insurance: "बीमा",
    loan: "ऋण",
    training: "प्रशिक्षण",
    infrastructure: "बुनियादी ढांचा",
    minimumLand: "न्यूनतम भूमि जोत",
    state: "राज्य",
    soilAdvisor: "मिट्टी सलाहकार",
    soilCrop: "मिट्टी-फसल मिलान",
  },
  [Language.TAMIL]: {
    appTitle: "கிசான் AI",
    welcome: "வணக்கம், விவசாயி",
    cropDoctor: "பயிர் மருத்துவர்",
    marketHub: "சந்தை விலை",
    weather: "வானிலை",
    aiAssistant: "AI உதவியாளர்",
    sustainableTips: "இயற்கை குறிப்புகள்",
    scanCrop: "பயிர் நோயை ஸ்கேன் செய்க",
    askAnything: "விவசாயம் பற்றி ஏதேனும் கேட்கவும்...",
    searchPlaceholder: "பயிர்கள், விலைகள் அல்லது நோய்களைத் தேடுக...",
    lowDataMode: "குறைந்த தரவு முறை",
    language: "மொழி",
    voiceActive: "கேட்கிறது...",
    uploadImage: "புகைப்படத்தை பதிவேற்றுக",
    analyze: "பகுப்பாய்வு செய்க",
    smartSearch: "ஸ்மார்ட் வாய்ஸ் தேடல்",
    alertCenter: "காலநிலை எச்சரிக்கை மையம்",
    sendSms: "அவசர SMS அனுப்புக",
    triggerAlarm: "பண்ணை அலாரம்",
    smsSuccess: "அவசர SMS அனுப்பப்பட்டது!",
    alarmPlaying: "அலாரம் ஒலிக்கிறது...",
    secureCropDesc: "திடீர் வானிலை மாற்றங்களிலிருந்து உங்கள் பயிரைக் காக்கவும்.",
    manageContacts: "தொடர்புகளை நிர்வகிக்கவும்",
    addContact: "அவசர எண்ணைச் சேர்க்கவும்",
    noContacts: "அவசர தொடர்புகள் எதுவும் சேர்க்கப்படவில்லை.",
    contactPlaceholder: "10 இலக்க மொபைல் எண்ணை உள்ளிடவும்",
    saveContact: "தொடர்பைச் சேமி",
    maxContacts: "நீங்கள் 3 அவசர தொடர்புகளைச் சேர்க்கலாம்.",
    voiceHelp: "குரல் உதவி",
    askQuestion: "உங்கள் கேள்வியைக் கேளுங்கள்...",
    helpTopics: "பிரபலமான தலைப்புகள்",
    speechToSpeech: "AI உடன் பேசுங்கள்",
    multiLangSearch: "பன்மொழி தேடல்",
    voiceSearchBtn: "குரல் மூலம் தேடுக",
    textSearchBtn: "உரை மூலம் தேடுக",
    farmLedger: "பண்ணை கணக்கு",
    schemeFinder: "அரசு திட்டங்கள்",
    voiceResponse: "குரல் உதவியாளர்",
    todaysTasks: "இன்றைய பணிகள்",
    addActivity: "செயல்பாட்டைச் சேர்",
    activityType: "செயல்பாடு வகை",
    cropName: "பயிர் பெயர்",
    activityDate: "தேதி",
    activityDetails: "விவரங்கள்",
    cost: "செலவு (₹)",
    yield: "மகசூல் (கி.கி)",
    notes: "குறிப்புகள்",
    noActivities: "செயல்பாடுகள் எதுவும் இல்லை",
    sowing: "விதைப்பு",
    irrigation: "நீர்ப்பாசனம்",
    fertilizer: "உரம் இடுதல்",
    pesticide: "பூச்சிக்கொல்லி தெளிப்பு",
    harvesting: "அறுவடை",
    weeding: "களை எடுத்தல்",
    pruning: "கத்தரித்தல்",
    other: "மற்றவை",
    eligibility: "தகுதி",
    benefits: "நன்மைகள்",
    applyNow: "விண்ணப்பிக்கவும்",
    deadline: "கடைசி தேதி",
    noSchemes: "திட்டங்கள் இல்லை",
    subsidy: "மானியம்",
    insurance: "காப்பீடு",
    loan: "கடன்",
    training: "பயிற்சி",
    infrastructure: "உள்கட்டமைப்பு",
    minimumLand: "குறைந்தபட்ச நிலம்",
    state: "மாநிலம்",
    soilAdvisor: "மண் ஆலோசகர்",
    soilCrop: "மண்-பயிர் பொருத்தம்",
  },
  [Language.KANNADA]: {
    appTitle: "ಕಿಸಾನ್ AI",
    welcome: "ನಮಸ್ಕಾರ, ರೈತ ಮಿತ್ರ",
    cropDoctor: "ಬೆಳೆ ವೈದ್ಯ",
    marketHub: "ಮಾರುಕಟ್ಟೆ ದರಗಳು",
    weather: "ಹವಾಮಾನ",
    aiAssistant: "AI ಸಹಾಯಕ",
    sustainableTips: "ಸಾವಯವ ಕೃಷಿ ಸಲಹೆಗಳು",
    scanCrop: "ಬೆಳೆ ರೋಗ ಪತ್ತೆ ಮಾಡಿ",
    askAnything: "ಕೃಷಿ ಬಗ್ಗೆ ಕೇಳಿ...",
    searchPlaceholder: "ಬೆಳೆಗಳು, ಬೆಲೆಗಳು ಅಥವಾ ರೋಗಗಳನ್ನು ಹುಡುಕಿ...",
    lowDataMode: "ಕಡಿಮೆ ಡೇಟಾ ಮೋಡ್",
    language: "ಭಾಷೆ",
    voiceActive: "ಆಲಿಸುತ್ತಿದೆ...",
    uploadImage: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    analyze: "ವಿಶ್ಲೇಷಿಸಿ",
    smartSearch: "ಸ್ಮಾರ್ಟ್ ಧ್ವನಿ ಹುಡುಕಾಟ",
    alertCenter: "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ ಕೇಂದ್ರ",
    sendSms: "ತುರ್ತು SMS ಕಳುಹಿಸಿ",
    triggerAlarm: "ಫಾರ್ಮ್ ಅಲಾರಾಂ",
    smsSuccess: "ತುರ್ತು SMS ಕಳುಹಿಸಲಾಗಿದೆ!",
    alarmPlaying: "ಅಲಾರಾಂ ಮೊಳಗುತ್ತಿದೆ...",
    secureCropDesc: "ಹಠಾತ್ ಹವಾಮಾನ ಬದಲಾವಣೆಗಳಿಂದ ನಿಮ್ಮ ಬೆಳೆಯನ್ನು ರಕ್ಷಿಸಿ.",
    manageContacts: "ಸಂಪರ್ಕಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    addContact: "ತುರ್ತು ಸಂಖ್ಯೆಯನ್ನು ಸೇರಿಸಿ",
    noContacts: "ಯಾವುದೇ ತುರ್ತು ಸಂಪರ್ಕಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ.",
    contactPlaceholder: "10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    saveContact: "ಸಂಪರ್ಕ ಉಳಿಸಿ",
    maxContacts: "ನೀವು 3 ತುರ್ತು ಸಂಪರ್ಕಗಳನ್ನು ಸೇರಿಸಬಹುದು.",
    voiceHelp: "ಧ್ವನಿ ಸಹಾಯ",
    askQuestion: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ...",
    helpTopics: "ಜನಪ್ರಿಯ ವಿಷಯಗಳು",
    speechToSpeech: "AI ಜೊತೆ ಮಾತನಾಡಿ",
    multiLangSearch: "ಬಹುಭಾಷಾ ಹುಡುಕಾಟ",
    voiceSearchBtn: "ಧ್ವನಿ ಮೂಲಕ ಹುಡುಕಿ",
    textSearchBtn: "ಪಠ್ಯದ ಮೂಲಕ ಹುಡುಕಿ",
    farmLedger: "ಕೃಷಿ ಲೆಕ್ಕಪತ್ರ",
    schemeFinder: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    voiceResponse: "ಧ್ವನಿ ಸಹಾಯಕ",
    todaysTasks: "ಇಂದಿನ ಕಾರ್ಯಗಳು",
    addActivity: "ಚಟುವಟಿಕೆ ಸೇರಿಸಿ",
    activityType: "ಚಟುವಟಿಕೆ ಪ್ರಕಾರ",
    cropName: "ಬೆಳೆಯ ಹೆಸರು",
    activityDate: "ದಿನಾಂಕ",
    activityDetails: "ವಿವರಗಳು",
    cost: "ವೆಚ್ಚ (₹)",
    yield: "ಇಳುವರಿ (ಕೆಜಿ)",
    notes: "ಟಿಪ್ಪಣಿಗಳು",
    noActivities: "ಯಾವುದೇ ಚಟುವಟಿಕೆಗಳಿಲ್ಲ",
    sowing: "ಬಿತ್ತನೆ",
    irrigation: "ನೀರಾವರಿ",
    fertilizer: "ಗೊಬ್ಬರ ಪ್ರಯೋಗ",
    pesticide: "ಕೀಟನಾಶಕ ಸಿಂಪಡಣೆ",
    harvesting: "ಕೊಯ್ಲು",
    weeding: "ಕಳೆ ತೆಗೆಯುವುದು",
    pruning: "ಸವರುವಿಕೆ",
    other: "ಇತರೆ",
    eligibility: "ಅರ್ಹತೆ",
    benefits: "ಪ್ರಯೋಜನಗಳು",
    applyNow: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    deadline: "ಕೊನೆಯ ದಿನಾಂಕ",
    noSchemes: "ಯಾವುದೇ ಯೋಜನೆಗಳಿಲ್ಲ",
    subsidy: "ಸಬ್ಸಿಡಿ",
    insurance: "ವಿಮೆ",
    loan: "ಸಾಲ",
    training: "ತರಬೇತಿ",
    infrastructure: "ಮೂಲಸೌಕರ್ಯ",
    minimumLand: "ಕನಿಷ್ಠ ಭೂಮಿ",
    state: "ರಾಜ್ಯ",
    soilAdvisor: "ಮಣ್ಣು ಸಲಹೆಗಾರ",
    soilCrop: "ಮಣ್ಣು-ಬೆಳೆ ಹೊಂದಾಣಿಕೆ",
  },
  [Language.MARATHI]: {
    appTitle: "किसान AI",
    welcome: "नमस्कार, शेतकरी मित्र",
    cropDoctor: "पीक डॉक्टर",
    marketHub: "बाजार भाव",
    weather: "हवामान",
    aiAssistant: "AI सहाय्यक",
    sustainableTips: "सेंद्रिय शेती सल्ला",
    scanCrop: "पीक रोग स्कॅन करा",
    askAnything: "शेतीबद्दल काहीही विचारा...",
    searchPlaceholder: "पिके, किंमती किंवा रोग शोधा...",
    lowDataMode: "कमी डेटा मोड",
    language: "भाषा",
    voiceActive: "ऐकत आहे...",
    uploadImage: "फोटो अपलोड करा",
    analyze: "विश्लेषण करा",
    smartSearch: "स्मार्ट व्हॉइस सर्च",
    alertCenter: "हवामान चेतावणी केंद्र",
    sendSms: "आपत्कालीन SMS पाठवा",
    triggerAlarm: "फार्म अलार्म",
    smsSuccess: "आपत्कालीन SMS पाठवला!",
    alarmPlaying: "अलार्म वाजत आहे...",
    secureCropDesc: "अचानक हवामान बदलांपासून आपल्या पिकाचे संरक्षण करा.",
    manageContacts: "संपर्क व्यवस्थापित करा",
    addContact: "आपत्कालीन क्रमांक जोडा",
    noContacts: "अद्याप कोणतेही संपर्क जोडलेले नाहीत.",
    contactPlaceholder: "10 अंकी मोबाइल नंबर",
    saveContact: "संपर्क जतन करा",
    maxContacts: "तुम्ही 3 आपत्कालीन संपर्क जोडू शकता.",
    voiceHelp: "व्हॉइस मदत",
    askQuestion: "वाचा प्रश्न विचारा...",
    helpTopics: "लोकप्रिय विषय",
    speechToSpeech: "AI शी बोला",
    multiLangSearch: "बहुभाषिक शोध",
    voiceSearchBtn: "आवाजाद्वारे शोधा",
    textSearchBtn: "मजकूराद्वारे शोधा",
    farmLedger: "शेताचा हिशोब",
    schemeFinder: "सरकारी योजना",
    voiceResponse: "व्हॉइस सहाय्यक",
    todaysTasks: "आजची कामे",
    addActivity: "काम जोडा",
    activityType: "कामाचा प्रकार",
    cropName: "पिकाचे नाव",
    activityDate: "तारीख",
    activityDetails: "तपशील",
    cost: "खर्च (₹)",
    yield: "उत्पादन (किलो)",
    notes: "टीपा",
    noActivities: "कोणतीही कामे नाहीत",
    sowing: "पेरणी",
    irrigation: "सिंचन",
    fertilizer: "खत",
    pesticide: "कीटकनाशक फवारणी",
    harvesting: "काढणी",
    weeding: "खुरपणी",
    pruning: "छाटणी",
    other: "इतर",
    eligibility: "पात्रता",
    benefits: "फायदे",
    applyNow: "अर्ज करा",
    deadline: "अंतिम मुदत",
    noSchemes: "योजना नाहीत",
    subsidy: "अनुदान",
    insurance: "विमा",
    loan: "कर्ज",
    training: "प्रशिक्षण",
    infrastructure: "पायाभूत सुविधा",
    minimumLand: "किमान जमीन",
    state: "राज्य",
    soilAdvisor: "माती सल्लागार",
    soilCrop: "माती-पीक जोडी",
  },

  [Language.BENGALI]: {
    appTitle: "কিসান AI",
    welcome: "স্বাগতম, কৃষক বন্ধু",
    cropDoctor: "ফসল ডাক্তার",
    marketHub: "বাজার দর",
    weather: "আবহাওয়া",
    aiAssistant: "AI সহকারী",
    sustainableTips: "জৈব কৃষি টিপস",
    scanCrop: "ফসলের রোগ স্ক্যান করুন",
    askAnything: "কৃষি সম্পর্কে কিছু জিজ্ঞাসা করুন...",
    searchPlaceholder: "ফসল, দাম বা রোগ খুঁজুন...",
    lowDataMode: "কম ডেটা মোড",
    language: "ভাষা",
    voiceActive: "শুনছি...",
    uploadImage: "ছবি আপলোড করুন",
    analyze: "বিশ্লেষণ করুন",
    smartSearch: "স্মার্ট ভয়েস সার্চ",
    alertCenter: "আবহাওয়া সতর্কতা কেন্দ্র",
    sendSms: "জরুরী SMS পাঠান",
    triggerAlarm: "ফার্ম অ্যালার্ম",
    smsSuccess: "জরুরী SMS পাঠানো হয়েছে!",
    alarmPlaying: "অ্যালার্ম বাজছে...",
    secureCropDesc: "হঠাৎ আবহাওয়া পরিবর্তন থেকে আপনার ফসল রক্ষা করুন।",
    manageContacts: "যোগাযোগ ব্যবস্থাপনা",
    addContact: "জরুরী নম্বর যোগ করুন",
    noContacts: "এখনও কোনও জরুরী যোগাযোগ যোগ করা হয়নি।",
    contactPlaceholder: "১০ অঙ্কের মোবাইল নম্বর লিখুন",
    saveContact: "যোগাযোগ সংরক্ষণ করুন",
    maxContacts: "আপনি ৩টি জরুরী যোগাযোগ যোগ করতে পারেন।",
    voiceHelp: "ভয়েস হেল্প",
    askQuestion: "আপনার প্রশ্ন জিজ্ঞাসা করুন...",
    helpTopics: "জনপ্রিয় বিষয়",
    speechToSpeech: "AI এর সাথে কথা বলুন",
    multiLangSearch: "বহুভাষিক অনুসন্ধান",
    voiceSearchBtn: "ভয়েস দ্বারা খুঁজুন",
    textSearchBtn: "টেক্সট দ্বারা খুঁজুন",
    farmLedger: "খামারের খাতা",
    schemeFinder: "সরকারি প্রকল্প",
    voiceResponse: "ভয়েস সহকারী",
    todaysTasks: "আজকের কাজ",
    addActivity: "কার্যকলাপ যোগ করুন",
    activityType: "কার্যকলাপের ধরন",
    cropName: "ফসলের নাম",
    activityDate: "তারিখ",
    activityDetails: "বিবরণ",
    cost: "খরচ (₹)",
    yield: "ফলন (কেজি)",
    notes: "নোট",
    noActivities: "কোনো কার্যকলাপ নেই",
    sowing: "বপন",
    irrigation: "সেচ",
    fertilizer: "সার প্রয়োগ",
    pesticide: "কীটনাশক স্প্রে",
    harvesting: "ফসল কাটা",
    weeding: "আগাছা দমন",
    pruning: "ছাঁটাই",
    other: "অন্যান্য",
    eligibility: "যোগ্যতা",
    benefits: "সুবিধা",
    applyNow: "আবেদন করুন",
    deadline: "শেষ তারিখ",
    noSchemes: "কোনো প্রকল্প নেই",
    subsidy: "ভর্তুকি",
    insurance: "বীমা",
    loan: "ঋণ",
    training: "প্রশিক্ষণ",
    infrastructure: "অবকাঠামো",
    minimumLand: "ন্যূনতম জমি",
    state: "রাজ্য",
    soilAdvisor: "মাটি পরামর্শদাতা",
    soilCrop: "মাটি-ফসল মিল",
  },
  [Language.MALAYALAM]: {
    appTitle: "കിസാൻ AI",
    welcome: "സ്വാഗതം, കർഷക സുഹൃത്തേ",
    cropDoctor: "വിള ഡോക്ടർ",
    marketHub: "വിപണി വിലകൾ",
    weather: "കാലാവസ്ഥ",
    aiAssistant: "AI അസിസ്റ്റന്റ്",
    sustainableTips: "ജൈവ കൃഷി നിർദ്ദേശങ്ങൾ",
    scanCrop: "വിള രോഗം പരിശോധിക്കുക",
    askAnything: "കൃഷിയെക്കുറിച്ച് ചോദിക്കുക...",
    searchPlaceholder: "വിളകൾ, വിലകൾ അല്ലെങ്കിൽ രോഗങ്ങൾ തിരയുക...",
    lowDataMode: "ലോ ഡാറ്റ മോഡ്",
    language: "ഭാഷ",
    voiceActive: "കേൾക്കുന്നു...",
    uploadImage: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    analyze: "വിശകലനം ചെയ്യുക",
    smartSearch: "സ്മാർട്ട് വോയിസ് സെർച്ച്",
    alertCenter: "കാലാവസ്ഥ മുന്നറിയിപ്പ് കേന്ദ്രം",
    sendSms: "അടിയന്തര SMS അയക്കുക",
    triggerAlarm: "ഫാം അലാറം",
    smsSuccess: "അടിയന്തര SMS അയച്ചു!",
    alarmPlaying: "അലാറം മുഴങ്ങുന്നു...",
    secureCropDesc: "പെട്ടെന്നുള്ള കാലാവസ്ഥാ മാറ്റങ്ങളിൽ നിന്ന് നിങ്ങളുടെ വിള സംരക്ഷിക്കുക.",
    manageContacts: "കോൺടാക്റ്റുകൾ നിയന്ത്രിക്കുക",
    addContact: "അടിയന്തര നമ്പർ ചേർക്കുക",
    noContacts: "ഇതുവരെ അടിയന്തര കോൺടാക്റ്റുകൾ ചേർത്തിട്ടില്ല.",
    contactPlaceholder: "10 അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    saveContact: "കോൺടാക്റ്റ് സംരക്ഷിക്കുക",
    maxContacts: "നിങ്ങൾക്ക് 3 അടിയന്തര കോൺടാക്റ്റുകൾ വരെ ചേർക്കാം.",
    voiceHelp: "വോയിസ് സഹായം",
    askQuestion: "നിങ്ങളുടെ ചോദ്യം ചോദിക്കുക...",
    helpTopics: "ജനപ്രിയ വിഷയങ്ങൾ",
    speechToSpeech: "AI-യോട് സംസാരിക്കുക",
    multiLangSearch: "ബഹുഭാഷാ തിരയൽ",
    voiceSearchBtn: "ശബ്ദം വഴി തിരയുക",
    textSearchBtn: "ടെക്സ്റ്റ് വഴി തിരയുക",
    farmLedger: "കർഷക കണക്ക്",
    schemeFinder: "സർക്കാർ പദ്ധതികൾ",
    voiceResponse: "വോയിസ് അസിസ്റ്റന്റ്",
    todaysTasks: "ഇന്നത്തെ ജോലികൾ",
    addActivity: "പ്രവർത്തനം ചേർക്കുക",
    activityType: "പ്രവർത്തന തരം",
    cropName: "വിളയുടെ പേര്",
    activityDate: "തീയതി",
    activityDetails: "വിശദാംശങ്ങൾ",
    cost: "ചെലവ് (₹)",
    yield: "വിളവ് (കിലോഗ്രാം)",
    notes: "കുറിപ്പുകൾ",
    noActivities: "പ്രവർത്തനങ്ങളൊന്നും ഇല്ല",
    sowing: "വിതയ്ക്കൽ",
    irrigation: "നനയ്കൽ",
    fertilizer: "വളം പ്രയോഗം",
    pesticide: "കീടനാശിനി തളിക്കൽ",
    harvesting: "വിളവെടുപ്പ്",
    weeding: "കള പറിക്കൽ",
    pruning: "വെട്ടിയൊതുക്കൽ",
    other: "മറ്റുള്ളവ",
    eligibility: "യോഗ്യത",
    benefits: "നേട്ടങ്ങൾ",
    applyNow: "അപേക്ഷിക്കുക",
    deadline: "അവസാന തീയതി",
    noSchemes: "പദ്ധതികൾ ലഭ്യമല്ല",
    subsidy: "സബ്‌സിഡി",
    insurance: "ഇൻഷുറൻസ്",
    loan: "വായ്പ",
    training: "പരിശീലനം",
    infrastructure: "അടിസ്ഥാന സൗകര്യങ്ങൾ",
    minimumLand: "കുറഞ്ഞ ഭൂമി",
    state: "സംസ്ഥാനം",
    soilAdvisor: "മണ്ണ് ഉപദേശകൻ",
    soilCrop: "മണ്ണ്-വിള ചേർച്ച",
  },
  [Language.GUJARATI]: {
    appTitle: "કિસાન AI",
    welcome: "સ્વાગત છે, ખેડૂત મિત્ર",
    cropDoctor: "પાક ડોક્ટર",
    marketHub: "બજાર ભાવ",
    weather: "હવામાન",
    aiAssistant: "AI મદદનીશ",
    sustainableTips: "સજીવ ખેતી ટિપ્સ",
    scanCrop: "પાક રોગ સ્કેન કરો",
    askAnything: "ખેતી વિશે પૂછો...",
    searchPlaceholder: "પાક, ભાવ અથવા રોગો શોધો...",
    lowDataMode: "ઓછો ડેટા મોડ",
    language: "ભાષા",
    voiceActive: "સાંભળી રહ્યું છે...",
    uploadImage: "ફોટો અપલોડ કરો",
    analyze: "વિશ્લેષણ કરો",
    smartSearch: "સ્માર્ટ વોઇસ સર્ચ",
    alertCenter: "હવામાન ચેતવણી કેન્દ્ર",
    sendSms: "ઇમરજન્સી SMS મોકલો",
    triggerAlarm: "ફાર્મ એલાર્મ",
    smsSuccess: "ઇમરજન્સી SMS મોકલવામાં આવ્યો!",
    alarmPlaying: "એલાર્મ વાગી રહ્યું છે...",
    secureCropDesc: "અચાનક હવામાન ફેરફારોથી તમારા પાકને સુરક્ષિત કરો.",
    manageContacts: "સંપર્કો મેનેજ કરો",
    addContact: "ઇમરજન્સી નંબર ઉમેરો",
    noContacts: "હજુ સુધી કોઈ ઇમરજન્સી સંપર્ક ઉમેર્યો નથી.",
    contactPlaceholder: "10 અંકનો મોબાઇલ નંબર દાખલ કરો",
    saveContact: "સંપર્ક સાચવો",
    maxContacts: "તમે 3 ઇમરજન્સી સંપર્કો ઉમેરી શકો છો.",
    voiceHelp: "વોઇસ મદદ",
    askQuestion: "તમારો પ્રશ્ન પૂછો...",
    helpTopics: "લોકપ્રિય વિષયો",
    speechToSpeech: "AI સાથે વાત કરો",
    multiLangSearch: "બહુભાષી શોધ",
    voiceSearchBtn: "અવાજ દ્વારા શોધો",
    textSearchBtn: "લખાણ દ્વારા શોધો",
    farmLedger: "ખેત હિસાબ",
    schemeFinder: "સરકારી યોજનાઓ",
    voiceResponse: "વોઇસ આસિસ્ટન્ટ",
    todaysTasks: "આજના કાર્યો",
    addActivity: "પ્રવૃત્તિ ઉમેરો",
    activityType: "પ્રવૃત્તિ પ્રકાર",
    cropName: "પાકનું નામ",
    activityDate: "તારીખ",
    activityDetails: "વિગતો",
    cost: "ખર્ચ (₹)",
    yield: "ઉપજ (કિલો)",
    notes: "નોંધો",
    noActivities: "કોઈ પ્રવૃત્તિઓ નથી",
    sowing: "વાવણી",
    irrigation: "પિયત",
    fertilizer: "ખાતર",
    pesticide: "જંતુનાશક છંટકાવ",
    harvesting: "કાપણી",
    weeding: "નિંદામણ",
    pruning: "છાંટણી",
    other: "અન્ય",
    eligibility: "લાયકાત",
    benefits: "ફાયદા",
    applyNow: "અરજી કરો",
    deadline: "છેલ્લી તારીખ",
    noSchemes: "કોઈ યોજનાઓ નથી",
    subsidy: "સબસિડી",
    insurance: "વીમો",
    loan: "લોન",
    training: "તાલીમ",
    infrastructure: "માળખાગત સુવિધા",
    minimumLand: "લઘુત્તમ જમીન",
    state: "રાજ્ય",
    soilAdvisor: "જમીન સલાહકાર",
    soilCrop: "જમીન-પાક મેચ",
  },
  [Language.PUNJABI]: {
    appTitle: "ਕਿਸਾਨ AI",
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ, ਕਿਸਾਨ ਵੀਰ",
    cropDoctor: "ਫਸਲ ਡਾਕਟਰ",
    marketHub: "ਮੰਡੀ ਰੇਟ",
    weather: "ਮੌਸਮ",
    aiAssistant: "AI ਸਹਾਇਕ",
    sustainableTips: "ਕੁਦਰਤੀ ਖੇਤੀ ਸੁਝਾਅ",
    scanCrop: "ਫਸਲ ਰੋਗ ਸਕੈਨ ਕਰੋ",
    askAnything: "ਖੇਤੀ ਬਾਰੇ ਪੁੱਛੋ...",
    searchPlaceholder: "ਫਸਲਾਂ, ਕੀਮਤਾਂ ਜਾਂ ਬਿਮਾਰੀਆਂ ਲੱਭੋ...",
    lowDataMode: "ਘੱਟ ਡਾਟਾ ਮੋਡ",
    language: "ਭਾਸ਼ਾ",
    voiceActive: "ਸੁਣ ਰਿਹਾ ਹੈ...",
    uploadImage: "ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    analyze: "ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    smartSearch: "ਸਮਾਰਟ ਵੌਇਸ ਖੋਜ",
    alertCenter: "ਮੌਸਮ ਚੇਤਾਵਨੀ ਕੇਂਦਰ",
    sendSms: "ਐਮਰਜੈਂਸੀ SMS ਭੇਜੋ",
    triggerAlarm: "ਫਾਰਮ ਅਲਾਰਮ",
    smsSuccess: "ਐਮਰਜੈਂਸੀ SMS ਭੇਜਿਆ ਗਿਆ!",
    alarmPlaying: "ਅਲਾਰਮ ਵੱਜ ਰਿਹਾ ਹੈ...",
    secureCropDesc: "ਅਚਾਨਕ ਮੌਸਮ ਬਦਲਾਅ ਤੋਂ ਆਪਣੀ ਫਸਲ ਬਚਾਓ।",
    manageContacts: "ਸੰਪਰਕ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
    addContact: "ਐਮਰਜੈਂਸੀ ਨੰਬਰ ਸ਼ਾਮਲ ਕਰੋ",
    noContacts: "ਅਜੇ ਕੋਈ ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਸ਼ਾਮਲ ਨਹੀਂ ਕੀਤਾ ਗਿਆ।",
    contactPlaceholder: "10 ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    saveContact: "ਸੰਪਰਕ ਸੇਵ ਕਰੋ",
    maxContacts: "ਤੁਸੀਂ 3 ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ ਸ਼ਾਮਲ ਕਰ ਸਕਦੇ ਹੋ।",
    voiceHelp: "ਵੌਇਸ ਮਦਦ",
    askQuestion: "ਆਪਣਾ ਸਵਾਲ ਪੁੱਛੋ...",
    helpTopics: "ਪ੍ਰਸਿੱਧ ਵਿਸ਼ੇ",
    speechToSpeech: "AI ਨਾਲ ਗੱਲ ਕਰੋ",
    multiLangSearch: "ਬਹੁਭਾਸ਼ਾਈ ਖੋਜ",
    voiceSearchBtn: "ਆਵਾਜ਼ ਦੁਆਰਾ ਲੱਭੋ",
    textSearchBtn: "ਟੈਕਸਟ ਦੁਆਰਾ ਲੱਭੋ",
    farmLedger: "ਖੇਤ ਖਾਤਾ",
    schemeFinder: "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
    voiceResponse: "ਵੌਇਸ ਸਹਾਇਕ",
    todaysTasks: "ਅੱਜ ਦੇ ਕੰਮ",
    addActivity: "ਗਤੀਵਿਧੀ ਸ਼ਾਮਲ ਕਰੋ",
    activityType: "ਗਤੀਵਿਧੀ ਕਿਸਮ",
    cropName: "ਫਸਲ ਦਾ ਨਾਮ",
    activityDate: "ਮਿਤੀ",
    activityDetails: "ਵੇਰਵੇ",
    cost: "ਲਾਗਤ (₹)",
    yield: "ਝਾੜ (ਕਿਲੋ)",
    notes: "ਨੋਟਸ",
    noActivities: "ਕੋਈ ਗਤੀਵਿਧੀਆਂ ਨਹੀਂ",
    sowing: "ਬਿਜਾਈ",
    irrigation: "ਸਿੰਚਾਈ",
    fertilizer: "ਖਾਦ",
    pesticide: "ਕੀਟਨਾਸ਼ਕ ਸਪਰੇਅ",
    harvesting: "ਕਟਾਈ",
    weeding: "ਨਦੀਨ",
    pruning: "ਕਾਂਟ-ਛਾਂਟ",
    other: "ਹੋਰ",
    eligibility: "ਯੋਗਤਾ",
    benefits: "ਲਾਭ",
    applyNow: "ਅਪਲਾਈ ਕਰੋ",
    deadline: "ਆਖਰੀ ਮਿਤੀ",
    noSchemes: "ਕੋਈ ਸਕੀਮਾਂ ਨਹੀਂ",
    subsidy: "ਸਬਸਿਡੀ",
    insurance: "ਬੀਮਾ",
    loan: "ਕਰਜ਼ਾ",
    training: "ਸਿਖਲਾਈ",
    infrastructure: "ਬੁਨਿਆਦੀ ਢਾਂਚਾ",
    minimumLand: "ਘੱਟੋ-ਘੱਟ ਜ਼ਮੀਨ",
    state: "ਰਾਜ",
    soilAdvisor: "ਮਿੱਟੀ ਸਲਾਹਕਾਰ",
    soilCrop: "ਮਿੱਟੀ-ਫਸਲ ਮੇਲ",
  }
};

export const MENU_ITEMS = [
  { id: 'dashboard', icon: <Sprout size={24} />, labelKey: 'welcome' },
  { id: 'chat', icon: <MessageSquare size={24} />, labelKey: 'aiAssistant' },
  { id: 'speech', icon: <Mic size={24} />, labelKey: 'speechToSpeech' },
  { id: 'voice', icon: <Volume2 size={24} />, labelKey: 'voiceResponse' },
  { id: 'doctor', icon: <ShieldAlert size={24} />, labelKey: 'cropDoctor' },
  { id: 'soil', icon: <Layers size={24} />, labelKey: 'soilAdvisor' },
  { id: 'market', icon: <ShoppingBag size={24} />, labelKey: 'marketHub' },
  { id: 'ledger', icon: <BookOpen size={24} />, labelKey: 'farmLedger' },
  { id: 'schemes', icon: <Zap size={24} />, labelKey: 'schemeFinder' },
  { id: 'tips', icon: <Leaf size={24} />, labelKey: 'sustainableTips' },
];
